version: '3.8'

services:
  frontend:
    build: .
    image: doric-explorer:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      - ../../envs/mainnet/common-frontend.env
    ports:
      - 3000:3000
