version: '3.8'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    # image: public.ecr.aws/i8r9u2u6/explorer-frontend:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      - ../../envs/mainnet/common-frontend.env
    ports:
      - 3000:3000
